### ISSUE TITLE
Cache search question

### ISSUE THREAD

**Issue by avra911** [rs-pro/mongoid-elasticsearch#21]
Hi,

I am doing a search and I am using kaminari as pagination
```ruby
def self.get_items(query_term, page, per_page)
    Rails.cache.fetch("#{query_term}/#{page}/#{per_page}", expires_in: 1.month) do
        ...
        @items = Model.es.search({body:@body}, {page: page, per_page: per_page})
```

and view:
```haml
@items.each do |item|
    ...
= paginate @items, :window => 1, :outer_window => 1
```

I was wonder how I can cache the ```@items```, because just doing the same way as with standard model cache throws me an error (```no _dump_data is defined for class Proc```):

Should I move the cache directive to view instead of model search function definition?

Thanks in advanced,
R

**Comment by avra911** [comment]
It appears that doing cache in view directly works:
```haml
- cache("#{params['q']}/#{params['page']}") do
    - @items.each do |item|
```

**Comment by glebtv** [comment]
Probably you should cache results

    Model.es.search({body:@body}, {page: page, per_page: per_page}).results.to_a
